### ISSUE TITLE
System does not start from uberjar with clojure-1.7.0

### ISSUE THREAD

**Issue by mbuczko** [stuartsierra/component#32]
I have a problem starting my components (a whole system actually) aot-ed and packed to uberjar with clojure 1.7.0 (beta3 and latest RC1). Switching clojure back to 1.6.0 and repackaging uberjar again solves the problem, so I guess there might be something wrong with component library itself :)

**Comment by ddossot** [comment]
Is there an exception being thrown?

**Comment by mbuczko** [comment]
nope, no exceptions. that's a bit mysterious because it looks like component/start simply does nothing.
I spent half a day disabling blocks of code trying to narrow this problem and when there was actually nothing more to remove I switched to clojure 1.6.0 in my dependencies and voila! system got initialized.

As mentioned, it's a bit tricky because this issue appears only when executing aot-ed uberjar.

**Comment by mbuczko** [comment]
I've created a simple project replicating this issue:

https://github.com/mbuczko/temp-component

it uses boot to create uberjar. if you use Mac, boot is available through Homebrew (brew install boot).

**Comment by stuartsierra** [comment]
I cannot reproduce this issue using Leiningen.

I was unable to build the project using boot. `boot uberjar` returned the error "boot: no boot.core dependency specified in build.boot"

I expect this is an AOT-compilation or uberjar issue and nothing to do with Component. Maybe your uberjar contains stale .class files compiled against the wrong version of Clojure.

**Comment by mbuczko** [comment]
Unfortunately, it's not the case. I was cleaning build dir (target/) each time before making new uberjar.
I'll take a look at boot problem that you mentioned in a second.

**Comment by stuartsierra** [comment]
I think it is very likely that this is an issue with your build configuration or environment, instead of a problem specifically with 'component'.

Since I cannot reproduce the behavior you are seeing, I suggest you ask about this problem on the [Clojure mailing list](https://groups.google.com/forum/#!forum/clojure), where a wider audience may have better suggestions on how to identify the cause.

If it does turn out to be a problem with 'component' I will do my best to fix it.

**Comment by mbuczko** [comment]
ok, thanks Stuart. I'll try to dig a bit deeper to see where the real problem is. I'm closing this issue now, and possibly will come back with more detailed investigation :)

**Comment by Skinney** [comment]
@mbuczko Did you figure this out? I'm having the exact same problem.

**Comment by dluksza** [comment]
@Skinney, same here.

@mbuczko did you found a workaround for this issue?

**Comment by stuartsierra** [comment]
I have been able to reproduce this issue using [Boot](https://github.com/boot-clj/boot). I have never reproduced it using Leiningen. I am fairly certain this is somehow related to the way Boot does AOT-compilation or builds uberJARs.

Similar issues have been reported for Boot: see https://github.com/boot-clj/boot/issues/193 and https://github.com/boot-clj/boot/issues/227. Some users report that the problem is resolved on the latest `master` branch of Boot.

**Comment by stuartsierra** [comment]
Possibly related to https://github.com/boot-clj/boot/issues/211 or https://github.com/boot-clj/boot/issues/217, both with fixes on Git `master` since Boot release 2.1.2.

Possibly also related to [CLJ-979](http://dev.clojure.org/jira/browse/CLJ-979) or [CLJ-1315](http://dev.clojure.org/jira/browse/CLJ-1315)

**Comment by Skinney** [comment]
Thanks @stuartsierra. Awaiting new release of boot.

**Comment by dluksza** [comment]
Just tried boot 2.1.2-23-g516f186 with clojure 1.7.0 and component 0.2.3 and it works fine!
