### ISSUE TITLE
Sub-systems and dependencies metadata issue

### ISSUE THREAD

**Issue by danstone** [stuartsierra/component#33]
If one wants to use a system as a component (not a common use case asfaik?) it is made difficult by the fact that components injected into the sub-system retain their metadata and therefore their dependencies (despite the fact the component will have already started with its dependencies assoc'd) so that when the sub-system is started, it fails as it thinks it needs to resolve the dependencies of the injected component. Would an easy fix be to move ::dependencies to a different key when a component is assoc'd into another?

I am happy to submit a PR for this if they are being accepted?

**Comment by stuartsierra** [comment]
I discourage nested systems because the semantics of system-to-system dependencies are unclear. I have yet to see a case where nested systems are actually necessary. See [Composing Stuart Sierra's components](https://groups.google.com/d/topic/clojure/2-baBp61XTs/discussion) (Clojure mailing list, March 2015) for more background.

I would be very reluctant to accept any changes to the dependency model at this point, as many people have built third-party tools on top of 'Component'.

**Comment by danstone** [comment]
I understand - and I did know that systems of systems was not encouraged, I can see that people have had similar problems before so thanks for pointing me at that post. 

To work around this, we have wrapped our system in a record where we manually inject the dependencies.
