### ISSUE TITLE
Question: Whether it should be okay to pass system record directly to a special component

### ISSUE THREAD

**Issue by sdegutis** [stuartsierra/component#46]
Quoth the readme:

> The "application" or "business logic" may itself be represented by one or more components.

My web application's "business logic" is represented by a single component. I also have a component for the web router, and about 10 other components representing external services (email service, database, etc).

Because of this, the "business logic" component needs every single other component (except the router component) in the system in order to do its job.

The simplest way to give these components to my "business logic" component is to give the system record directly to the "business logic" component, rather than superfluously handing over *every single other component* in the system (aside from itself and the router component) when defining and initializing the "business logic" component.

Yet, your readme says:

> The top-level "system" record is intended to be used exclusively for starting and stopping other components. No component in the system should depend directly on its parent system.

> I do not intend that application functions should receive the top-level system as an argument. Rather, functions are defined in terms of components. Each component receives references only to the components on which it depends.

What do you suggest be done in this case, if not to give it the system record directly? Should they each be given to my "business logic" component independently? That seems excessive, so I'm wondering if you have a better idea in mind, based on the phrasing of your readme.

**Comment by stuartsierra** [comment]
Use whatever works. Ultimately, it's all just maps and records, so as long as you know what you're doing you can use a system map in place of a component map.

If your "business logic" depends on *every* component in the system, then I would look for opportunities to decouple that logic from some of those components.

Please direct further questions to the [Clojure mailing list](https://groups.google.com/forum/#!forum/clojure) instead of GitHub issues, as questions are more likely to be seen and answered there.
