### ISSUE TITLE
:extend-via-metadata in 0.4.0 breaks on ClojureScript < 1.10.516

### ISSUE THREAD

**Issue by rschmukler** [stuartsierra/component#63]
The new changes in `0.4.0` break component with clojurescript compilers (both shadow-cljs and clojurescript). It seems the [cljs macro](https://cljs.github.io/api/cljs.core/defprotocol) hasn't caught up yet.

Since it's the only change in `0.4.0`, it's not hard to use `0.3.2` instead.

**Comment by stuartsierra** [comment]
Thanks for the report. Leaving this open as a notice until the ClojureScript compilers catch up, which I expect will happen soon.

**Comment by stuartsierra** [comment]
I believe this was fixed in ClojureScript as of [1.10.516](https://github.com/clojure/clojurescript/blob/8a5abc4e02c72d000204674f38c6665c786302a4/changes.md) on January 31, 2018; via [ClojureScript change log](https://github.com/clojure/clojurescript/blob/master/changes.md).

Component 0.4.0 is still not backwards-compatible with earlier versions of ClojureScript; projects on older ClojureScript should use Component 0.3.2 instead.
